MCU = atmega32u4
BOOTLOADER = atmel-dfu

SPLIT_KEYBOARD = yes

BACKLIGHT_ENABLE = no
RGBLIGHT_DRIVER = WS2812
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_DRIVER = WS2812

# Remove unneeded features
EXTRAKEY_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
LTO_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
